version: '3'
services:
    fossology:
        container_name: fossology
        image: fossology/fossology:3.10.0
        ports:
            - 7100:80
        networks:
            - resus
    license-engine:
        container_name: license-engine
        build: .
        ports:
            - 7000:7000
        networks:
            - resus
        environment:
            - FOSSOLOGY_ENDPOINT_BASE_PATH=http://fossology:80
networks:
  resus:
    driver: bridge
